// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: osparsed.proto

// Protobuf Java Version: 3.25.2
package com.bms.kos.kafka;

public final class KOSParsed {
  private KOSParsed() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KOSLogEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bms.KOSLogEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string hostName = 1;</code>
     * @return The hostName.
     */
    java.lang.String getHostName();
    /**
     * <code>string hostName = 1;</code>
     * @return The bytes for hostName.
     */
    com.google.protobuf.ByteString
        getHostNameBytes();

    /**
     * <code>string processName = 2;</code>
     * @return The processName.
     */
    java.lang.String getProcessName();
    /**
     * <code>string processName = 2;</code>
     * @return The bytes for processName.
     */
    com.google.protobuf.ByteString
        getProcessNameBytes();

    /**
     * <code>string processId = 3;</code>
     * @return The processId.
     */
    java.lang.String getProcessId();
    /**
     * <code>string processId = 3;</code>
     * @return The bytes for processId.
     */
    com.google.protobuf.ByteString
        getProcessIdBytes();

    /**
     * <code>string serviceName = 4;</code>
     * @return The serviceName.
     */
    java.lang.String getServiceName();
    /**
     * <code>string serviceName = 4;</code>
     * @return The bytes for serviceName.
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    /**
     * <code>.google.protobuf.Timestamp logDateTime = 5;</code>
     * @return Whether the logDateTime field is set.
     */
    boolean hasLogDateTime();
    /**
     * <code>.google.protobuf.Timestamp logDateTime = 5;</code>
     * @return The logDateTime.
     */
    com.google.protobuf.Timestamp getLogDateTime();
    /**
     * <code>.google.protobuf.Timestamp logDateTime = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getLogDateTimeOrBuilder();
  }
  /**
   * Protobuf type {@code bms.KOSLogEntry}
   */
  public static final class KOSLogEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bms.KOSLogEntry)
      KOSLogEntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KOSLogEntry.newBuilder() to construct.
    private KOSLogEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KOSLogEntry() {
      hostName_ = "";
      processName_ = "";
      processId_ = "";
      serviceName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new KOSLogEntry();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bms.kos.kafka.KOSParsed.internal_static_bms_KOSLogEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bms.kos.kafka.KOSParsed.internal_static_bms_KOSLogEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bms.kos.kafka.KOSParsed.KOSLogEntry.class, com.bms.kos.kafka.KOSParsed.KOSLogEntry.Builder.class);
    }

    private int bitField0_;
    public static final int HOSTNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object hostName_ = "";
    /**
     * <code>string hostName = 1;</code>
     * @return The hostName.
     */
    @java.lang.Override
    public java.lang.String getHostName() {
      java.lang.Object ref = hostName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostName_ = s;
        return s;
      }
    }
    /**
     * <code>string hostName = 1;</code>
     * @return The bytes for hostName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHostNameBytes() {
      java.lang.Object ref = hostName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROCESSNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object processName_ = "";
    /**
     * <code>string processName = 2;</code>
     * @return The processName.
     */
    @java.lang.Override
    public java.lang.String getProcessName() {
      java.lang.Object ref = processName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        processName_ = s;
        return s;
      }
    }
    /**
     * <code>string processName = 2;</code>
     * @return The bytes for processName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProcessNameBytes() {
      java.lang.Object ref = processName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROCESSID_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object processId_ = "";
    /**
     * <code>string processId = 3;</code>
     * @return The processId.
     */
    @java.lang.Override
    public java.lang.String getProcessId() {
      java.lang.Object ref = processId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        processId_ = s;
        return s;
      }
    }
    /**
     * <code>string processId = 3;</code>
     * @return The bytes for processId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProcessIdBytes() {
      java.lang.Object ref = processId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICENAME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object serviceName_ = "";
    /**
     * <code>string serviceName = 4;</code>
     * @return The serviceName.
     */
    @java.lang.Override
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      }
    }
    /**
     * <code>string serviceName = 4;</code>
     * @return The bytes for serviceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGDATETIME_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp logDateTime_;
    /**
     * <code>.google.protobuf.Timestamp logDateTime = 5;</code>
     * @return Whether the logDateTime field is set.
     */
    @java.lang.Override
    public boolean hasLogDateTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp logDateTime = 5;</code>
     * @return The logDateTime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getLogDateTime() {
      return logDateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : logDateTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp logDateTime = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getLogDateTimeOrBuilder() {
      return logDateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : logDateTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hostName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(processName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, processName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(processId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, processId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, serviceName_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(5, getLogDateTime());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hostName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(processName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, processName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(processId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, processId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, serviceName_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getLogDateTime());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bms.kos.kafka.KOSParsed.KOSLogEntry)) {
        return super.equals(obj);
      }
      com.bms.kos.kafka.KOSParsed.KOSLogEntry other = (com.bms.kos.kafka.KOSParsed.KOSLogEntry) obj;

      if (!getHostName()
          .equals(other.getHostName())) return false;
      if (!getProcessName()
          .equals(other.getProcessName())) return false;
      if (!getProcessId()
          .equals(other.getProcessId())) return false;
      if (!getServiceName()
          .equals(other.getServiceName())) return false;
      if (hasLogDateTime() != other.hasLogDateTime()) return false;
      if (hasLogDateTime()) {
        if (!getLogDateTime()
            .equals(other.getLogDateTime())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getHostName().hashCode();
      hash = (37 * hash) + PROCESSNAME_FIELD_NUMBER;
      hash = (53 * hash) + getProcessName().hashCode();
      hash = (37 * hash) + PROCESSID_FIELD_NUMBER;
      hash = (53 * hash) + getProcessId().hashCode();
      hash = (37 * hash) + SERVICENAME_FIELD_NUMBER;
      hash = (53 * hash) + getServiceName().hashCode();
      if (hasLogDateTime()) {
        hash = (37 * hash) + LOGDATETIME_FIELD_NUMBER;
        hash = (53 * hash) + getLogDateTime().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bms.kos.kafka.KOSParsed.KOSLogEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bms.kos.kafka.KOSParsed.KOSLogEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bms.kos.kafka.KOSParsed.KOSLogEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bms.kos.kafka.KOSParsed.KOSLogEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bms.kos.kafka.KOSParsed.KOSLogEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bms.kos.kafka.KOSParsed.KOSLogEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bms.kos.kafka.KOSParsed.KOSLogEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bms.kos.kafka.KOSParsed.KOSLogEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.bms.kos.kafka.KOSParsed.KOSLogEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.bms.kos.kafka.KOSParsed.KOSLogEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bms.kos.kafka.KOSParsed.KOSLogEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bms.kos.kafka.KOSParsed.KOSLogEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bms.kos.kafka.KOSParsed.KOSLogEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bms.KOSLogEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bms.KOSLogEntry)
        com.bms.kos.kafka.KOSParsed.KOSLogEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bms.kos.kafka.KOSParsed.internal_static_bms_KOSLogEntry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bms.kos.kafka.KOSParsed.internal_static_bms_KOSLogEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bms.kos.kafka.KOSParsed.KOSLogEntry.class, com.bms.kos.kafka.KOSParsed.KOSLogEntry.Builder.class);
      }

      // Construct using com.bms.kos.kafka.KOSParsed.KOSLogEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLogDateTimeFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        hostName_ = "";
        processName_ = "";
        processId_ = "";
        serviceName_ = "";
        logDateTime_ = null;
        if (logDateTimeBuilder_ != null) {
          logDateTimeBuilder_.dispose();
          logDateTimeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bms.kos.kafka.KOSParsed.internal_static_bms_KOSLogEntry_descriptor;
      }

      @java.lang.Override
      public com.bms.kos.kafka.KOSParsed.KOSLogEntry getDefaultInstanceForType() {
        return com.bms.kos.kafka.KOSParsed.KOSLogEntry.getDefaultInstance();
      }

      @java.lang.Override
      public com.bms.kos.kafka.KOSParsed.KOSLogEntry build() {
        com.bms.kos.kafka.KOSParsed.KOSLogEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bms.kos.kafka.KOSParsed.KOSLogEntry buildPartial() {
        com.bms.kos.kafka.KOSParsed.KOSLogEntry result = new com.bms.kos.kafka.KOSParsed.KOSLogEntry(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.bms.kos.kafka.KOSParsed.KOSLogEntry result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.hostName_ = hostName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.processName_ = processName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.processId_ = processId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.serviceName_ = serviceName_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.logDateTime_ = logDateTimeBuilder_ == null
              ? logDateTime_
              : logDateTimeBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bms.kos.kafka.KOSParsed.KOSLogEntry) {
          return mergeFrom((com.bms.kos.kafka.KOSParsed.KOSLogEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bms.kos.kafka.KOSParsed.KOSLogEntry other) {
        if (other == com.bms.kos.kafka.KOSParsed.KOSLogEntry.getDefaultInstance()) return this;
        if (!other.getHostName().isEmpty()) {
          hostName_ = other.hostName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getProcessName().isEmpty()) {
          processName_ = other.processName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getProcessId().isEmpty()) {
          processId_ = other.processId_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getServiceName().isEmpty()) {
          serviceName_ = other.serviceName_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasLogDateTime()) {
          mergeLogDateTime(other.getLogDateTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                hostName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                processName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                processId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                serviceName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getLogDateTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object hostName_ = "";
      /**
       * <code>string hostName = 1;</code>
       * @return The hostName.
       */
      public java.lang.String getHostName() {
        java.lang.Object ref = hostName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hostName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hostName = 1;</code>
       * @return The bytes for hostName.
       */
      public com.google.protobuf.ByteString
          getHostNameBytes() {
        java.lang.Object ref = hostName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hostName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hostName = 1;</code>
       * @param value The hostName to set.
       * @return This builder for chaining.
       */
      public Builder setHostName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        hostName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string hostName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHostName() {
        hostName_ = getDefaultInstance().getHostName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string hostName = 1;</code>
       * @param value The bytes for hostName to set.
       * @return This builder for chaining.
       */
      public Builder setHostNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        hostName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object processName_ = "";
      /**
       * <code>string processName = 2;</code>
       * @return The processName.
       */
      public java.lang.String getProcessName() {
        java.lang.Object ref = processName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          processName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string processName = 2;</code>
       * @return The bytes for processName.
       */
      public com.google.protobuf.ByteString
          getProcessNameBytes() {
        java.lang.Object ref = processName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          processName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string processName = 2;</code>
       * @param value The processName to set.
       * @return This builder for chaining.
       */
      public Builder setProcessName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        processName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string processName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProcessName() {
        processName_ = getDefaultInstance().getProcessName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string processName = 2;</code>
       * @param value The bytes for processName to set.
       * @return This builder for chaining.
       */
      public Builder setProcessNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        processName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object processId_ = "";
      /**
       * <code>string processId = 3;</code>
       * @return The processId.
       */
      public java.lang.String getProcessId() {
        java.lang.Object ref = processId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          processId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string processId = 3;</code>
       * @return The bytes for processId.
       */
      public com.google.protobuf.ByteString
          getProcessIdBytes() {
        java.lang.Object ref = processId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          processId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string processId = 3;</code>
       * @param value The processId to set.
       * @return This builder for chaining.
       */
      public Builder setProcessId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        processId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string processId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearProcessId() {
        processId_ = getDefaultInstance().getProcessId();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string processId = 3;</code>
       * @param value The bytes for processId to set.
       * @return This builder for chaining.
       */
      public Builder setProcessIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        processId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object serviceName_ = "";
      /**
       * <code>string serviceName = 4;</code>
       * @return The serviceName.
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string serviceName = 4;</code>
       * @return The bytes for serviceName.
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serviceName = 4;</code>
       * @param value The serviceName to set.
       * @return This builder for chaining.
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        serviceName_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string serviceName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearServiceName() {
        serviceName_ = getDefaultInstance().getServiceName();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string serviceName = 4;</code>
       * @param value The bytes for serviceName to set.
       * @return This builder for chaining.
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        serviceName_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp logDateTime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> logDateTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp logDateTime = 5;</code>
       * @return Whether the logDateTime field is set.
       */
      public boolean hasLogDateTime() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp logDateTime = 5;</code>
       * @return The logDateTime.
       */
      public com.google.protobuf.Timestamp getLogDateTime() {
        if (logDateTimeBuilder_ == null) {
          return logDateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : logDateTime_;
        } else {
          return logDateTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp logDateTime = 5;</code>
       */
      public Builder setLogDateTime(com.google.protobuf.Timestamp value) {
        if (logDateTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          logDateTime_ = value;
        } else {
          logDateTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp logDateTime = 5;</code>
       */
      public Builder setLogDateTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (logDateTimeBuilder_ == null) {
          logDateTime_ = builderForValue.build();
        } else {
          logDateTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp logDateTime = 5;</code>
       */
      public Builder mergeLogDateTime(com.google.protobuf.Timestamp value) {
        if (logDateTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            logDateTime_ != null &&
            logDateTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getLogDateTimeBuilder().mergeFrom(value);
          } else {
            logDateTime_ = value;
          }
        } else {
          logDateTimeBuilder_.mergeFrom(value);
        }
        if (logDateTime_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp logDateTime = 5;</code>
       */
      public Builder clearLogDateTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        logDateTime_ = null;
        if (logDateTimeBuilder_ != null) {
          logDateTimeBuilder_.dispose();
          logDateTimeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp logDateTime = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getLogDateTimeBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getLogDateTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp logDateTime = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getLogDateTimeOrBuilder() {
        if (logDateTimeBuilder_ != null) {
          return logDateTimeBuilder_.getMessageOrBuilder();
        } else {
          return logDateTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : logDateTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp logDateTime = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getLogDateTimeFieldBuilder() {
        if (logDateTimeBuilder_ == null) {
          logDateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getLogDateTime(),
                  getParentForChildren(),
                  isClean());
          logDateTime_ = null;
        }
        return logDateTimeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bms.KOSLogEntry)
    }

    // @@protoc_insertion_point(class_scope:bms.KOSLogEntry)
    private static final com.bms.kos.kafka.KOSParsed.KOSLogEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bms.kos.kafka.KOSParsed.KOSLogEntry();
    }

    public static com.bms.kos.kafka.KOSParsed.KOSLogEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KOSLogEntry>
        PARSER = new com.google.protobuf.AbstractParser<KOSLogEntry>() {
      @java.lang.Override
      public KOSLogEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<KOSLogEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KOSLogEntry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bms.kos.kafka.KOSParsed.KOSLogEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bms_KOSLogEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bms_KOSLogEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016osparsed.proto\022\003bms\032\037google/protobuf/t" +
      "imestamp.proto\"\215\001\n\013KOSLogEntry\022\020\n\010hostNa" +
      "me\030\001 \001(\t\022\023\n\013processName\030\002 \001(\t\022\021\n\tprocess" +
      "Id\030\003 \001(\t\022\023\n\013serviceName\030\004 \001(\t\022/\n\013logDate" +
      "Time\030\005 \001(\0132\032.google.protobuf.TimestampB\036" +
      "\n\021com.bms.kos.kafkaB\tKOSParsedb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_bms_KOSLogEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bms_KOSLogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bms_KOSLogEntry_descriptor,
        new java.lang.String[] { "HostName", "ProcessName", "ProcessId", "ServiceName", "LogDateTime", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
